config/routes.rb
Rails.application.routes.draw do

  get 'user/:id', to: 'user#id', as: "user_id"
  get 'welcome/:id', to: 'welcome#id', as: 'welcome_id'
  get 'static_pages/home', to: 'static_pages#home'
  get 'static_pages/team', to: 'static_pages#team'
  get 'static_pages/contact', to: 'static_pages#contact'

  resources :gossip
  resources :cities
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, :zip_code, presence: true 
  validates :zip_code, length: { in: 3..16}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes

  validates :content, 
    length: {maximum: 287}, 
    presence: true 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user 
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :user, :title, :content, presence: true
end

app/models/join_message_recipient.rb
class JoinMessageRecipient < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  belongs_to :tag 
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips 

  validates :title, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :first_name, :last_name, :email, :age, 
  presence: true 
  validates :description, length: {maximum: 500}
  validates :email,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def show
    @gossips = Gossip.all
    @i=params[:id]
    @city = City.find(params[:id])
    @city_gossips = []
    Gossip.all.each do |gossip|
      @city_gossips << gossip if gossip.user.city.id == @city.id
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def index show
  end 

  def show
  end 

  def new
    @gossip = Gossip.new(title: params[:title],content: params[:content])
  end

  def create 
    @gossip = Gossip.new(user: User.last, title: params[:title],content: params[:content])
    if @gossip.save
      redirect_to static_pages_home_path, notice: "Tu as crée un nouveau potin."
    else 
      render 'new'
      flash.alert = "Il y a un problème, recommence"
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit
      flash.alert = "Il y a un problème, recommence"
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      redirect_to static_pages_home_path
    else
      render :edit
      flash.alert = "Il y a un problème, recommence"
    end
  end

  private 

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end 

end
 

app/controllers/user_controller.rb
class UserController < ApplicationController

  def id
    @user = User.find(params[:id])
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def id
    params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<div class="container">
<h1>Ville : <%= @city.name%> </h1>
<div class="album py-5 ">
    <div class="row">
      <% @city_gossips.each do |gossip| %>
        <div class="col-md-4">
          <div class="card" style="width: 80%;">
            <div class="card-body">
              <h5 class="card-title"><%=gossip.title%></h5>
              <h6 class="card-subtitle mb-2 text-muted">By <%=gossip.user.first_name%></h6>
              <p class="card-text"><%=gossip.content%></p>
              <a href="#" class="card-link"><%= link_to "Read more", gossip_path(gossip.id) %></a>
            </div>
          </div>
        <br>
        </div>
      <% end %>
    </div>  
</div>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossip/edit.html.erb
<h1> Editer le potin </h1>

<%= form_for @gossip do |f| %>
<div class="form-group">
  <label> Titre du potin </label>
<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <label> Contenu du potin </label>
<%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form-group">
  <button type="submit" class="btn btn-primary"> Modifier le potin </button>
</div> 

<% end %> 

app/views/gossip/new.html.erb
<html>
  <body>
    <!-- ... -->
    <% flash.each do |type, msg| %>
    <div class="alert alert-danger" role="alert">
    <%= msg %>
    </div>
    <% end %>

    <%= form_tag url_for(action: 'create'), method: "gossip" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Body' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>

    <!-- ... -->
  </body>
</html>

app/views/gossip/show.html.erb
    <div class="card">
      <div class="card-body">
    <h1>T'as gagné petit commère </h1>
    <br>
    <h2>Voici ton potin : </h2>
    <br>
        <% i = params[:id] %>
        <% g = Gossip.find(i) %>
      <p><strong>Titre</strong> <br> <%= g.title %></p>
        <p><strong>Potin </strong><br> <%= g.content %> </p>
        <p><strong>Créé le </strong><br> <%= g.created_at %> </p>
        <p><strong>Auteur </strong> <br> <%= g.user.first_name %> </p>
        <% user = g.user %>

      <div class="form-group">
        <button type="submit" class="btn btn-primary"> 
          <%= link_to "Profil de l'auteur", user_id_path(user.id) %> Profil de l'auteur
        </button>
        <br>
        <br>
        <div class="form-group">
        <button type="submit" class="btn btn-primary"> 
          <%= link_to "Modifier le gossip", edit_gossip_path(g.id) %> Modifier le gossip
        </button>
        <br>
        <br>
        <div class="form-group">
          <button type="submit" class="btn btn-danger"> 
            <p> <%= link_to "Supprimer le gossip", g,  :method => "delete", :title => "gossip supprimé" %> </p> 
          </button>
        </div>
      </div>
    </div>
   </body>
</html>

app/views/user/id.html.erb
<div class="card">
  <div class="card-body">
    <h1>Auteur</h1>
    <% i=params[:id] %>
    <% u = User.find(i) %>
    <br>
    <p><strong>Prénom</strong> <br> <%= u.first_name %></p>
    <br>

    <p><strong>Nom</strong> <br> <%= u.last_name %></p>
    <br>
    <p><strong>Age</strong> <br> <%= u.age %></p>
    <br>
    <p><strong>Description</strong> <br> <%= u.description %></p>
    <br>
    <p><strong>Email</strong> <br> <%= u.email %></p>
    <br>
    <p><strong>Ville</strong> <br> <%= u.city.name %>
    <%= link_to "Clique ici pour voir les potins de cette ville", city_path(u.city.id) %>

    </p>
  </div>
</div>
</body>
</html>