config/routes.rb
Rails.application.routes.draw do

  get 'user/:id', to: 'user#id', as: "user_id"
  get 'welcome/:id', to: 'welcome#id', as: 'welcome_id'
  get 'static_pages/home', to: 'static_pages#home'
  get 'static_pages/team', to: 'static_pages#team'
  get 'static_pages/contact', to: 'static_pages#contact'

  resources :gossip
  resources :cities
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, :zip_code, presence: true 
  validates :zip_code, length: { in: 3..16}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes

  validates :content, 
    length: {maximum: 287}, 
    presence: true 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user 
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :user, :title, :content, presence: true
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  belongs_to :tag 
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips 

  validates :title, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :first_name, :last_name, :email, :age, 
  presence: true 
  validates :description, length: {maximum: 500}
  validates :email,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def show
    @gossips = Gossip.all
    @i=params[:id]
    @city = City.find(params[:id])
    @city_gossips = []
    Gossip.all.each do |gossip|
      @city_gossips << gossip if gossip.user.city.id == @city.id
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def id
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>TheGossipProject</title>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
          <li class="nav-item active">
              <%= link_to "Accueil", static_pages_home_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Team", static_pages_team_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">    
              <%= link_to "Contact", static_pages_contact_path, :class => "nav-link"%>
          </li>
          </ul>
      </div>
      </nav>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>